<?php

// Gerado a partir de resources/js/data/anamnese.js (formulário de acolhimento infantil).
return [
    'Dados de identificação' => [
        'Nome',
        'Data de nascimento',
        'Idade',
        'Religião',
        'Cidade',
        'Estado',
        'Endereço',
        'Estado civil',
        'Sexo',
        'Escolaridade',
        'Telefone fixo',
        'Celular',
        'Recado',
        'Encaminhamento',
        'Profissional responsável pelo encaminhamento',
        'Busca independente (Sim/Não) — Recomendação',
    ],
    'Dados de identificação dos pais' => [
        'Nome do pai',
        'Idade do pai',
        'Profissão do pai',
        'Empresa do pai',
        'Escolaridade',
        'Nome da mãe',
        'Idade da mãe',
        'Profissão da mãe',
        'Empresa da mãe',
        'Endereço',
    ],
    'Queixa principal' => [
        'Queixa principal',
    ],
    'História clínica' => [
        'Doença crônica (Sim/Não) — Quais',
        'Laudo/Diagnóstico',
        'CID',
        'Há quanto tempo recebeu o diagnóstico',
        'Primeiros sinais que apresentou',
        'Quem percebeu os sinais (Família/Escola/Outros)',
        'Relate sobre',
    ],
    'Medicamentos e intervenções' => [
        'Uso de medicamentos (Sim/Não) — Quais',
        'Quanto tempo',
        'Casos de internação',
        'Motivo',
        'Limitações (auditiva, visual, motora, fala, outra)',
        'Psicoterapia / Psiquiatra / Neurologista',
        'Já procurou outros especialistas? Quais?',
        'Está fazendo tratamento médico, psicológico, psiquiátrico ou neurológico?',
        'Por quê?',
        'A criança tem/teve convulsões (com ou sem febre)?',
        'Já teve traumatismo?',
        'Já realizou alguma cirurgia? Qual?',
    ],
    'Período gestacional e pós-parto' => [
        'Problemas de saúde na gestação',
        'Condições emocionais na gestação e pós-parto',
        'Eventos significativos neste período',
    ],
    'Dados do nascimento' => [
        'Peso',
        'Centímetros',
        'Apgar',
        'Coloração',
        'Relate se houve problemas pós-parto',
    ],
    'Comunicação' => [
        'Comunicação atual (se fala, quantas palavras, atraso na linguagem, primeiras vocalizações, etc.)',
        'Balbucios',
        'Presença de ecolalias (Sim/Não) — Outros/quais',
    ],
    'Motricidade' => [
        'Sentar',
        'Engatinhar',
        'Andar',
        'Caminhar na ponta dos pés (Sim/Não) — Quanto tempo',
    ],
    'Alimentação' => [
        'Amamentação (Sim/Não) — Quanto tempo',
        'Mamadeiras (Sim/Não) — Quanto tempo',
        'A criança é forçada a se alimentar? Explique',
        'Seletividade alimentar (texturas, gosto, cor, temperatura, outros)',
        'Recebe ajuda na alimentação?',
    ],
    'Sono' => [
        'A criança dorme bem?',
        'Como é seu sono (agitado, tranquilo)',
        'Range os dentes ao dormir?',
        'Dorme em quarto separado dos pais?',
    ],
    'Autonomia' => [
        'Veste-se sozinho?',
        'Toma banho sozinho?',
        'Controle de esfíncteres',
        'Fez ou faz uso de fraldas? Quanto tempo',
        'Como foi o desfralde',
        'Chupetas — quanto tempo',
        'Como foi a retirada',
    ],
    'História familiar' => [
        'Dinâmica familiar',
        'Relação com os pais',
        'Relação com irmãos',
        'Presença de transtornos e/ou deficiências na família',
    ],
    'História social' => [
        'Prefere brincar sozinha(o) ou com amigos?',
        'Descreva o brincar do seu filho(a)',
        'Faz amigos com facilidade?',
        'Adapta-se facilmente ao meio?',
        'Escola (socialização)',
        'Rotina da criança (atividades extras, etc.)',
    ],
    'Dados escolares' => [
        'Dados da escola (ano de inserção, período, queixas, dificuldades, etc.)',
        'A criança gosta de ir à escola?',
        'É bem aceita pelos amigos ou é isolada?',
        'Casos de reprovação / áreas de dificuldades',
    ],
    'Comportamento' => [
        'Características predominantes (agressiva, passiva, dependente, independente, inquieta, medrosa, retraída, desligada, excitada, outros)',
        'Como reage quando contrariada?',
        'Eventos significativos',
        'Autoagressão — quais e comportamento que antecede o ocorrido',
        'Heteroagressão — quais e comportamento que antecede o ocorrido',
        'Comportamentos destrutivos — quais e comportamento que antecede o ocorrido',
        'Movimentos estereotipados (flap de mãos, balanço, etc.) — quais',
        'Alinhamento / empilhamento / gosta de objetos que rodam ou piscam',
        'Outros',
    ],
    'Medidas disciplinares' => [
        'Quais as medidas disciplinares normalmente utilizadas com a criança?',
        'Quem as usa?',
        'Quais as reações da criança frente a essas medidas?',
    ],
    'Preferências e reforços' => [
        'Atividades / brinquedos preferidos',
    ],
];
