<?php

// Pacientes de exemplo (os mesmos do protótipo do front).
return [
    [
        'nome' => 'Maria Aparecida',
        'cpf' => '12345678901',
        'telefone' => '(48) 99123-4501',
        'email' => 'maria.aparecida@email.com',
        'data_nascimento' => '1990-03-14',
        'sexo' => 'feminino',
        'endereco' => 'Rua das Palmeiras, 210 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Particular',
        'contato_emergencia_nome' => 'José Aparecida (esposo)',
        'contato_emergencia_telefone' => '(48) 99900-1111',
        'status_paciente' => 'ativo',
        'criado_em' => '2025-01-10',
        'matricula' => ['dia' => 'segunda-feira', 'horario' => '08:00', 'tipo' => 'presencial', 'valor' => 200],
    ],
    [
        'nome' => 'Pedro Silva',
        'cpf' => '23456789012',
        'telefone' => '(48) 99123-4502',
        'email' => 'pedro.silva@email.com',
        'data_nascimento' => '1988-07-22',
        'sexo' => 'masculino',
        'endereco' => 'Av. Centenário, 1450 — Pio Corrêa',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Unimed',
        'contato_emergencia_nome' => 'Ana Silva (irmã)',
        'contato_emergencia_telefone' => '(48) 99900-2222',
        'status_paciente' => 'ativo',
        'criado_em' => '2026-05-15',
        'matricula' => ['dia' => 'terça-feira', 'horario' => '10:00', 'tipo' => 'online', 'valor' => 180],
    ],
    [
        'nome' => 'Jorge Sousa',
        'cpf' => '34567890123',
        'telefone' => '(48) 99123-4503',
        'email' => 'jorge.sousa@email.com',
        'data_nascimento' => '1995-11-05',
        'sexo' => 'masculino',
        'endereco' => 'Rua Coronel Pedro Benedet, 88 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Particular',
        'contato_emergencia_nome' => 'Marta Sousa (mãe)',
        'contato_emergencia_telefone' => '(48) 99900-3333',
        'status_paciente' => 'ativo',
        'criado_em' => '2026-03-02',
        'matricula' => ['dia' => 'quarta-feira', 'horario' => '11:00', 'tipo' => 'presencial', 'valor' => 220],
    ],
    [
        'nome' => 'Patrícia Alves',
        'cpf' => '45678901234',
        'telefone' => '(48) 99123-4504',
        'email' => 'patricia.alves@email.com',
        'data_nascimento' => '1979-01-30',
        'sexo' => 'feminino',
        'endereco' => 'Rua Marechal Deodoro, 675 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Bradesco Saúde',
        'contato_emergencia_nome' => 'Carlos Alves (filho)',
        'contato_emergencia_telefone' => '(48) 99900-4444',
        'status_paciente' => 'ativo',
        'criado_em' => '2024-11-20',
        'matricula' => ['dia' => 'quinta-feira', 'horario' => '12:00', 'tipo' => 'presencial', 'valor' => 200],
    ],
    [
        'nome' => 'Luísa Silva',
        'cpf' => '56789012345',
        'telefone' => '(48) 99123-4505',
        'email' => 'luisa.silva@email.com',
        'data_nascimento' => '1992-09-18',
        'sexo' => 'feminino',
        'endereco' => 'Rua Henrique Lage, 320 — Próspera',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Particular',
        'contato_emergencia_nome' => 'Beatriz Silva (mãe)',
        'contato_emergencia_telefone' => '(48) 99900-5555',
        'status_paciente' => 'inativo',
        'criado_em' => '2026-02-14',
    ],
    [
        'nome' => 'Mike Pereira',
        'cpf' => '67890123456',
        'telefone' => '(48) 99123-4506',
        'email' => 'mike.pereira@email.com',
        'data_nascimento' => '2000-08-02',
        'sexo' => 'masculino',
        'endereco' => 'Rua Fernando Machado, 55 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'SulAmérica',
        'contato_emergencia_nome' => 'Sandra Pereira (mãe)',
        'contato_emergencia_telefone' => '(48) 99900-6666',
        'status_paciente' => 'ativo',
        'criado_em' => '2026-08-05',
        'matricula' => ['dia' => 'segunda-feira', 'horario' => '14:00', 'tipo' => 'presencial', 'valor' => 220],
    ],
    [
        'nome' => 'Ana Carolina Santos',
        'cpf' => '78901234567',
        'telefone' => '(48) 99123-4507',
        'email' => 'ana.carolina@email.com',
        'data_nascimento' => '1985-12-27',
        'sexo' => 'feminino',
        'endereco' => 'Rua Gustavo Richard, 140 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Particular',
        'contato_emergencia_nome' => 'Rafael Santos (esposo)',
        'contato_emergencia_telefone' => '(48) 99900-7777',
        'status_paciente' => 'ativo',
        'criado_em' => '2024-06-18',
        'matricula' => ['dia' => 'terça-feira', 'horario' => '09:00', 'tipo' => 'presencial', 'valor' => 200],
    ],
    [
        'nome' => 'João Silva',
        'cpf' => '89012345678',
        'telefone' => '(48) 99123-4508',
        'email' => 'joao.silva@email.com',
        'data_nascimento' => '1993-06-09',
        'sexo' => 'masculino',
        'endereco' => 'Rua Desembargador Pedro Silva, 402 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Amil',
        'contato_emergencia_nome' => 'Renata Silva (esposa)',
        'contato_emergencia_telefone' => '(48) 99900-8888',
        'status_paciente' => 'ativo',
        'criado_em' => '2026-04-22',
        'matricula' => ['dia' => 'quarta-feira', 'horario' => '10:00', 'tipo' => 'online', 'valor' => 180],
    ],
    [
        'nome' => 'Maria Cardoso',
        'cpf' => '90123456789',
        'telefone' => '(48) 99123-4509',
        'email' => 'maria.cardoso@email.com',
        'data_nascimento' => '1983-02-11',
        'sexo' => 'feminino',
        'endereco' => 'Rua Felipe Schmidt, 96 — Centro',
        'endereco_cidade' => 'Criciúma',
        'endereco_uf' => 'SC',
        'convenio' => 'Particular',
        'contato_emergencia_nome' => 'Paulo Cardoso (esposo)',
        'contato_emergencia_telefone' => '(48) 99900-9999',
        'status_paciente' => 'inativo',
        'criado_em' => '2025-09-10',
    ],
];
